
import { AppWrapper } from '@/my-ui/root/AppWrapper'
import './globals.css'
import { Inter } from 'next/font/google'
import { getPBCookieUser } from '@/state/pb/server_component_pb'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'App',
  description: 'Generated by create next app',
}

export default async function RootLayout({children,}: {children: React.ReactNode}) {
const user = await getPBCookieUser()
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppWrapper user={user}>
          {children}
        </AppWrapper>
      </body>
    </html>
  )

}
